### ISSUE TITLE
[BUG] Plugin is dead on 1.17

### ISSUE THREAD

**Issue by erxdev** [ThiccIndustries/Minecraft-Backdoor#13]
But version 1.3 is working ☺

[22:54:40] [Server thread/INFO]: [NoPos] Enabling NoPos v1.1*
[22:54:40] [Server thread/INFO]: Ready to disable F3 coordinates !
[22:54:40] [Server thread/ERROR]: Error occurred while enabling NoPos v1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/thiccindustries/backdoor/Backdoor$5 (wrong name: com/thiccindustries/backdoor/Config)
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:192) ~[patched_1.17.jar:git-Purpur-1255]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Purpur-1255]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.thiccindustries.backdoor.Backdoor.<init>(Backdoor.java:28) ~[?:?]
	at fr.rkode.nopos.NoPos.onEnable(NoPos.java:25) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:962) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Purpur-1255]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[patched_1.17.jar:git-Purpur-1255]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1255]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:54:40] [Server thread/INFO]: [NoPos] Disabling NoPos v1.1

**Comment by MajesticWaffle** [comment]
Fixed in v1.4.1, thanks.
