### ISSUE TITLE
Injector Error

### ISSUE THREAD

**Issue by wendellmeset** [ThiccIndustries/Minecraft-Backdoor#3]
whenever I try to use the injector, everything goes well but when it starts to inject, it says "Error while reading plugins meta data" or "Failed to read plugins meta data", it gives me that error for pretty much every plugin, and i need a fix please and ty!

**Comment by wendellmeset** [comment]
@MajesticWaffle

**Comment by MajesticWaffle** [comment]
Can you run the injector with the command line with the command `java -jar backdoor-1.2.jar` then copy paste the error from the console? It contains much more detailed error info for me. Thanks!

**Comment by MajesticWaffle** [comment]
Also tell me the plugin associated with the error log you send

**Comment by wendellmeset** [comment]
@MajesticWaffle the plugin associated is every single plugin ive tried (clearlag, 2 customs, aacfree, nocheat-plus)

**Comment by wendellmeset** [comment]
```
[Injector] Unknown error whilst parsing plugin YAML.
java.io.FileNotFoundException: \\C\Users\my-username\Downloads\Minecraft-Backdoor-Injector\Clearlag.jar (The network path was not found)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:167)
        at java.util.jar.JarFile.<init>(JarFile.java:104)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
        at com.thiccindustries.backdoor.Injector.readPluginYAML(Injector.java:186)
        at com.thiccindustries.backdoor.Injector.patchFile(Injector.java:68)
        at com.thiccindustries.backdoor.InjectorGUI.main(InjectorGUI.java:109)
Exception in thread "main" org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
        at com.thiccindustries.backdoor.Injector.readPluginYAML(Injector.java:194)
        at com.thiccindustries.backdoor.Injector.patchFile(Injector.java:68)
        at com.thiccindustries.backdoor.InjectorGUI.main(InjectorGUI.java:109)
Caused by: java.io.IOException: Stream closed
        at java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:166)
        at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
        ... 16 more

```

@MajesticWaffle thats the exact error

**Comment by MajesticWaffle** [comment]
Thank you for the stack trace, what version of windows and java are you running?

(You can find your java version by typing `java -version` in the command prompt)

**Comment by MajesticWaffle** [comment]
Bug resolved.
Please download version 1.3.
