### ISSUE TITLE
BackDoor Injection failed

### ISSUE THREAD

**Issue by ThnksCJ** [ThiccIndustries/Minecraft-Backdoor#39]
<br>
<br>**Describe the bug**<br>
the Backdoor fails when i try to inject it into a plugin

<br>**To Reproduce**<br>
1. Inject into [[Plugin]](https://www.spigotmc.org/resources/bountyhunters-legacy.40610/) for Minecraft 1.14
2. Run 
4. doesnt inject and fails
5. 
![image](https://user-images.githubusercontent.com/89362919/144087267-4ea1882f-0da5-450f-b533-e01baa0e4fb8.png)

<br>**Desktop (please complete the following information):**<br>
 - OS: windows
- Java Version:16.0.2

**Comment by MajesticWaffle** [comment]
Hi, the backdoor works correctly on my machine.
Please use the following command in command prompt to run the backdoor with additional output
`java -jar Backdoor-2.0.jar` (be sure to change directory into the same location as the backdoor jar)
Copy paste the resulting output in command prompt here.

**Comment by ThnksCJ** [comment]
thank you this fixed my issuse but the commands dont work ingame?

**Comment by MajesticWaffle** [comment]
Um. That shouldn't have changed anything, just produce a more detailed error message. 

Could you send the patched jar the injector made?

Reinject with a fake username if you want to censor that.

**Comment by ThnksCJ** [comment]
[19:53:02 INFO]: [BountyHunters] Enabling BountyHunters v2.2.6
[19:53:02 INFO]: [BountyHunters] Detected Server Version: v1_17_R1
[19:53:02 ERROR]: [BountyHunters] Your server version is not handled with NMS.
[19:53:03 ERROR]: [BountyHunters] Couldn't load Vault. Disabling...
[19:53:03 INFO]: [BountyHunters] Disabling BountyHunters v2.2.6
[19:53:03 ERROR]: Error occurred while enabling BountyHunters v2.2.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/thiccindustries/debugger/Debugger
        at net.Indyuce.bountyhunters.BountyHunters.onEnable(BountyHunters.java:188) ~[BountyHunters-2.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]

**Comment by MajesticWaffle** [comment]
Based on your server log, it seems you are trying to load a 1.14 plugin on 1.17, the plugin is failed to load because of incompatibilities which also causes the backdoor not to load.

[Please try with a plugin known working for 1.17](https://www.spigotmc.org/wiki/spigot-1-17-plugin-compatibility-list/)
