### ISSUE TITLE
[BUG] Error while starting

### ISSUE THREAD

**Issue by PerchunPak** [ThiccIndustries/Minecraft-Backdoor#40]
```
[20:10:39 ERROR]: Error occurred while enabling ChatEx v2.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: javassist/DirClassPath
        at javassist.ClassPoolTail.makePathObject(ClassPoolTail.java:267) ~[?:?]
        at javassist.ClassPoolTail.appendClassPath(ClassPoolTail.java:249) ~[?:?]
        at javassist.ClassPool.appendClassPath(ClassPool.java:1004) ~[?:?]
        at com.thiccindustries.debugger.Injector.patchFile(Injector.java:146) ~[?:?]
        at com.thiccindustries.debugger.Debugger.<init>(Debugger.java:70) ~[?:?]
        at de.jeter.chatex.ChatEx.onEnable(ChatEx.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[kSpigot.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.ClassNotFoundException: javassist.DirClassPath
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_311]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[kSpigot.jar:git-Paper-33d42c8e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
        ... 17 more
```

**Comment by MajesticWaffle** [comment]
Looks like a class from the javassist library that needs to be added to the resource paths in Injector.java.

I added all the ones needed on my end, maybe that one is only needed on windows?

 Either way, that should fix it.

**Comment by PerchunPak** [comment]
So I tried reproduce it with debug messages, and seems like it is because plugin doesn't delete files after first patch, which ended with exception (example "File already in process")
Maybe it isn't good idea to replace patched files while server running, I need more read about how plugins auto update it self.

**Comment by PerchunPak** [comment]
Full log https://pastebin.com/TBtBNuhP
Interesting that error `NoClassDefFoundError` raises every time with different class

**Comment by PerchunPak** [comment]
Okay, I read. As I understand, auto update works because plugin didn't initialize fully. But backdoor trying replace plugins which already fully initialized.
All what you can do as I understand, it is add "Yes|No inject in other plugins" menu when injecting plugin, and then try to find system that will replace plugins jars after their stop or like this.

**Comment by MajesticWaffle** [comment]
Merged and released as [Version 2.1](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/V2.1)

**Comment by PerchunPak** [comment]
Doesn't fix issue with fail spreading thought server plugins, I only added switch to change this option.

**Comment by MajesticWaffle** [comment]
I'll leave this open for any other problems related to infection.

I also changed the option to warn that the feature is experimental.

**Comment by MajesticWaffle** [comment]
I'm guessing your specific problem is that on windows, different parts of the java assist library are needed. 

Could you run
`java -Xlog:class+load=info:classloaded.txt -jar Backdoor-2.1.jar`
And inject a plugin (with infection enabled) and upload classloaded.txt (contains all classes loaded by the jvm)?

**Comment by PerchunPak** [comment]
Sorry for long time without answer
```
Unrecognized option: -Xlog:class+load=info:classloaded.txt
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by PerchunPak** [comment]
Oops, I was on Java 8.
https://pastebin.com/dtLTfFsp

**Comment by nullsoepic** [comment]
With spreading enabled upon starting the server it fails to spread, and the plugin that was infected with the Injector does not work. This is the part of the plugins loading. https://pastebin.com/raw/U6kgDuLt The only plugins on the server are LuckPerms and ProtocolLib(infected). Both plugins work as if they were just downloaded, but neither seem to be infected

**Comment by MajesticWaffle** [comment]
@nullsoepic 
This is a certified "Im-a-dipshit" moment. will be fixed soon.

**Comment by MajesticWaffle** [comment]
@nullsoepic Should be fixed in [v2.2.3](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v2.2.3)

**Comment by erxson** [comment]
![image](https://user-images.githubusercontent.com/50082485/175824019-f2beef3b-8df4-44d6-9d52-b690c6e8d2ee.png)
spreading doesn't work? Temp folder created and these weird tmp files, but any jar doesn`t contain any of backdoor files

**Comment by erxson** [comment]
https://paste.gg/p/anonymous/987dbd321dd84966ba99701dc72c3094/files/38415c419a46493c8e3ae9aa8e0642af/raw

**Comment by PerchunPak** [comment]
> spreading doesn't work on windows?

Actually, spreading just doesn't work.

**Comment by erxson** [comment]
Is it hard to unload plugin, before infecting?
