### ISSUE TITLE
[BUG] NoClassDefFoundError: javassist/ClassPath after patch any file

### ISSUE THREAD

**Issue by PerchunPak** [ThiccIndustries/Minecraft-Backdoor#43]
After trying patch any file with gui.
```java
Exception in thread "main" java.lang.NoClassDefFoundError: javassist/ClassPath
        at com.thiccindustries.debugger.InjectorGUI.main(InjectorGUI.java:122)
Caused by: java.lang.ClassNotFoundException: javassist.ClassPath
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by PerchunPak** [comment]
Seems like you doesn't include libraries in package file.
Size of 2.1 is 35kb, and 2.0 almost 10mb

**Comment by MajesticWaffle** [comment]
Yeah i fucked up, [2.1 re-released with the correct jar](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/V2.1)
