### ISSUE TITLE
[BUG] BUG can't injection

### ISSUE THREAD

**Issue by diocan** [ThiccIndustries/Minecraft-Backdoor#52]
os windows 10 
plugin LPC [luckyperms chat]
all console [POWERSHELL]
PS C:\Users\giovannilongo\Desktop> java -jar .\backdoor-2.1.jar
[Injector] Reading plugin data for file: LPC.jar
C:\Users\giovannilongo\Desktop\LPC.jar
[Injector] Found plugin name: LPC
[Injector] Found main class: me.oncode9.lpc.LPCPlugin
[Injector] Injecting resources.
    (1/16) Debugger.class
    (2/16) Debugger$1.class
    (3/16) Debugger$2.class
    (4/16) Debugger$3.class
    (5/16) Debugger$4.class
    (6/16) Debugger$5.class
    (7/16) Debugger$6.class
    (8/16) Debugger$7.class
    (9/16) Debugger$8.class
    (10/16) Debugger$9.class
    (11/16) Debugger$10.class
    (12/16) Debugger$11.class
    (13/16) Config.class
    (14/16) Config$HelpItem.class
    (15/16) Injector.class
    (16/16) Injector$SimpleConfig.class
[Injector] Injecting backdoor loader into class.
{ new com.thiccindustries.debugger.Debugger(this, true, new String[]{"PandaWurst"}, "\", false); }
[Injector] Unknown Javassist error.
javassist.CannotCompileException: [source error] syntax error near " false); }"
        at javassist.CtBehavior.insertAfter(CtBehavior.java:877)
        at javassist.CtBehavior.insertAfter(CtBehavior.java:792)
        at com.thiccindustries.debugger.Injector.patchFile(Injector.java:190)
        at com.thiccindustries.debugger.InjectorGUI.main(InjectorGUI.java:123)
Caused by: compile error: syntax error near " false); }"
        at javassist.compiler.Parser.parsePrimaryExpr(Parser.java:1258)
        at javassist.compiler.Parser.parsePostfix(Parser.java:1031)
        at javassist.compiler.Parser.parseUnaryExpr(Parser.java:888)
        at javassist.compiler.Parser.parseBinaryExpr(Parser.java:775)
        at javassist.compiler.Parser.parseConditionalExpr(Parser.java:719)
        at javassist.compiler.Parser.parseExpression(Parser.java:699)
        at javassist.compiler.Parser.parseArgumentList(Parser.java:1332)
        at javassist.compiler.Parser.parseNew(Parser.java:1281)
        at javassist.compiler.Parser.parsePrimaryExpr(Parser.java:1244)
        at javassist.compiler.Parser.parsePostfix(Parser.java:1031)
        at javassist.compiler.Parser.parseUnaryExpr(Parser.java:888)
        at javassist.compiler.Parser.parseBinaryExpr(Parser.java:775)
        at javassist.compiler.Parser.parseConditionalExpr(Parser.java:719)
        at javassist.compiler.Parser.parseExpression(Parser.java:699)
        at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:591)
        at javassist.compiler.Parser.parseStatement(Parser.java:277)
        at javassist.compiler.Parser.parseBlock(Parser.java:289)
        at javassist.compiler.Parser.parseStatement(Parser.java:243)
        at javassist.compiler.Javac.compileStmnt(Javac.java:565)
        at javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:892)
        at javassist.CtBehavior.insertAfter(CtBehavior.java:851)
        ... 3 more

**Comment by MajesticWaffle** [comment]
Are you not using any chat prefix? That will cause problems.

**Comment by diocan** [comment]
work on tab plugin love this tool <3

**Comment by MajesticWaffle** [comment]
Is this fixed?
Please re-open if not.
