### ISSUE TITLE
[BUG] Infected plugin won't initialize

### ISSUE THREAD

**Issue by DarkReaper231** [ThiccIndustries/Minecraft-Backdoor#62]
<br>**Describe the bug**<br>
When I inject the plugin, I receive errors in the console
Only happens when spreading is enabled

<br>**To Reproduce**<br>
1. Inject into AntiCheatReloaded for Minecraft 1.18.1 (enabled spreading)
2. Run server
3. See error in console

<br>**Expected behavior**<br>
Shouldn't write any errors in console

<br>**Desktop (please complete the following information):**<br>
 - OS: Linux
- Java Version: 1.17, tried 1.8 but it doesn't seem to matter

<br>**Server Console Log**<br>
```
[15:36:33 ERROR]: Error occurred while enabling AntiCheatReloaded v1.11.0-PRE (Is it up to date?)
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for !@UTF8; exception=Invalid tag: !@UTF8
 in 'reader', line 111, column 3:
    - !@UTF8
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:336) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:391) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:375) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:534) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:480) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:461) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[snakeyaml-1.30.jar:?]
	at com.thiccindustries.debugger.Injector.readPluginYAML(Injector.java:257) ~[DarkAC-1.18-pre.jar:?]
	at com.thiccindustries.debugger.Injector.patchFile(Injector.java:72) ~[DarkAC-1.18-pre.jar:?]
	at com.thiccindustries.debugger.Debugger.<init>(Debugger.java:72) ~[DarkAC-1.18-pre.jar:?]
	at com.rammelkast.anticheatreloaded.AntiCheatReloaded.onEnable(AntiCheatReloaded.java:198) ~[DarkAC-1.18-pre.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1562]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Invalid tag: !@UTF8
	at org.yaml.snakeyaml.nodes.Tag.getClassName(Tag.java:125) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:664) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:323) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332) ~[snakeyaml-1.30.jar:?]
	... 32 more
[15:36:33 INFO]: [AntiCheatReloaded] Disabling AntiCheatReloaded v1.11.0-PRE
```

**Comment by MajesticWaffle** [comment]
It looks like it's running into a problem with the plugin.yaml of another plugin it's attempting to inject. Could you list all other plugins on the server?

**Comment by DarkReaper231** [comment]
> It looks like it's running into a problem with the plugin.yaml of another plugin it's attempting to inject. Could you list all other plugins on the server?

Here you go:

```
BetterRTP-3.2.1-4.jar
DecentHolograms-2.2.7.jar
EssentialsXChat-2.19.3-dev+27-bc2da98.jar
EssentialsXProtect-2.19.3-dev+27-bc2da98.jar
EssentialsXSpawn-2.19.3-dev+27-bc2da98.jar
EssentialsX-2.19.3-dev+27-bc2da98.jar
FastAsyncWorldEdit-Bukkit-2.0.2-SNAPSHOT-100.jar
LuckPerms-Bukkit-5.4.4.jar
MOTD.jar
Multiverse-Core-4.3.2-SNAPSHOT.jar
Multiverse-Inventories-4.2.3-SNAPSHOT.jar
Multiverse-NetherPortals-4.2.2-SNAPSHOT.jar
Multiverse-Portals-4.2.2-SNAPSHOT.jar
PlaceholderAPI-2.11.1.jar
PlotSquared-Bukkit-6.5.1-SNAPSHOT.jar
ProtocolLib.jar
SkinsRestorer.jar
TAB.v3.0.2.jar
UserLogin.jar
Vault.jar
VoidGen-2.2.1.jar
VoidSpawn.jar
worldguard-bukkit-7.0.6-dist.jar
```

**Comment by MajesticWaffle** [comment]
Could you please reinject the plugin using the [Injector Version 2.2.2](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v2.2.2) with Debug mode on, then resend the log?

**Comment by DarkReaper231** [comment]
This time with debugger enabled it throws this error
```
[14:10:21 INFO]: [MOTD] [Injector] Injecting backdoor loader into class.
[14:10:21 INFO]: [MOTD] { new com.thiccindustries.debugger.Debugger(this, true, new String[]{"test"}, "#", true,true); }
[14:10:21 ERROR]: Error occurred while enabling MOTD v2.3.8 (Is it up to date?)
java.lang.NoClassDefFoundError: javassist/bytecode/stackmap/TypeData$ArrayType
	at javassist.bytecode.stackmap.TypeData$ArrayElement.make(TypeData.java:668) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.Tracer.doOpcode0_53(Tracer.java:236) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:74) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164) ~[MOTD-patched.jar:?]
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108) ~[MOTD-patched.jar:?]
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:456) ~[MOTD-patched.jar:?]
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:438) ~[MOTD-patched.jar:?]
	at javassist.CtBehavior.insertAfter(CtBehavior.java:871) ~[MOTD-patched.jar:?]
	at javassist.CtBehavior.insertAfter(CtBehavior.java:792) ~[MOTD-patched.jar:?]
	at com.thiccindustries.debugger.Injector.patchFile(Injector.java:190) ~[MOTD-patched.jar:?]
	at com.thiccindustries.debugger.Debugger.<init>(Debugger.java:72) ~[MOTD-patched.jar:?]
	at com.yapzhenyie.motd.Motd.onEnable(Motd.java:47) ~[MOTD-patched.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: javassist.bytecode.stackmap.TypeData$ArrayType
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 27 more
```

**Comment by MajesticWaffle** [comment]
@DarkReaper231 
Looking though the code, Its a case of Im-a-dipshit. Will be fixed soon.

**Comment by timof121** [comment]
it looks like ur missing a javaassist library

**Comment by DarkReaper231** [comment]
> it looks like ur missing a javaassist library

Yeah it was. It has been fixed already

**Comment by DarkReaper231** [comment]
Btw I no longer come into issues in this report so I think it has been resolved
Closing
